### ISSUE TITLE
Set up personal machine 

### ISSUE THREAD

**Issue by Stephanie-P-Ball** [cs481-ekh/f22-ai-cbl#49]
As a developer, I want to set up my personal machine, so that I can run our programs

## Definition of Done
- [x] Have IDE downloaded and be able to run program
- [x] Be able to open up a Jupyter Notebook from IDE

## Tasks
- [x] Download Pycharm
- [x] Create environment for project
