### ISSUE TITLE
Create Linear Regression Analysis

### ISSUE THREAD

**Issue by Stephanie-P-Ball** [cs481-ekh/f22-ai-cbl#75]
As a developer, I want to create a linear regression analysis, so that I can predict knee stress and strain

# Definition of Done
- [x] Have a working Linear Regression Model

## Tasks
- [x] Create Linear Regression Model
- [x] Determine accuracy rate
