### ISSUE TITLE
Evaluate initial features

### ISSUE THREAD

**Issue by ninanikitina** [cs481-ekh/f22-ai-cbl#97]
As a machine learning engineer, I want to have clean data so that I can run liner regression analysis.

## Definition of Done
- [ ] New data table for training with no more than 10 features is created 

## Tasks
- [ ] Create and analyze heat-map correlation matrix for all features
- [ ] Check the distribution of predicted variables and remove outliers
- [ ] Choose the best features for analysis
